version: '3.9'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: postgres

volumes:
  data:
